#+TITLE:     OCCT: Scratch
#+AUTHOR:    David Conner
#+EMAIL:     noreply@te.xel.io
#+DESCRIPTION: notes

Repo for testing occt + emacs +org-babel. The goal is to enable loading the
environment for passing TCL scripts to OCCT from org-mode.

This should allow the generation of fairly simple shapes with simple operations
-- but anything more complex than fillets with edge specification or simple
boolean operations will probably require code that's unmaintainable. The idea
behind the workflow is to use OCCT to /parametrically/ produce simple models
which can be imported into other CAD programs.

* Notes

Either use =buffer-env= or =guix shell -Df guix.scm= to establish the
environment.

** OCCT Environment

Run =ls -al $GUIX_ENVIRONMENT= after loading =guix shell= to see what's there.

*** Env Scripts

+ $GUIX_ENVIRONMENT/bin/custom_gcc_64.sh
+ $GUIX_ENVIRONMENT/bin/custom.sh
+ $GUIX_ENVIRONMENT/bin/DRAWEXE
+ $GUIX_ENVIRONMENT/bin/draw.sh
+ $GUIX_ENVIRONMENT/bin/env.sh

** OCCT Tests

+ The =DRAWEXE= application basically is the test harness.
+ See [[https://dev.opencascade.org/doc/overview/html/occt_user_guides__test_harness.html][Draw Test Harness]] in docs and Doxygen for [[https://dev.opencascade.org/doc/refman/html/class_draw.html][Draw class]].

** OCCT Draw

Running =draw.sh= starts a console and the GUI. To do so, it loads the =env.sh=,
=custom.sh=, and =custom_gcc_64.sh= scripts, in order. In the console or GUI,
you'll need to run =pload ALL= to load all (some?) functionality.

#+begin_quote
NOTE: either some environment details are not being properly loaded. e.g. some
GUI interactions are not enabled. Perhaps some packages are missing from the
=guix.scm= propagated inputs.
#+end_quote

*** TCL Commands

TCL commands are entered into the console.

**** Draw [[https://dev.opencascade.org/doc/overview/html/occt_user_guides__test_harness.html#occt_draw_3_1][general commands]]

+ pload :: load script/module
+ help :: get help on commands
+ help help :: get help on help
+ spy :: record TCL macros into a file

**** [[https://dev.opencascade.org/doc/overview/html/occt_user_guides__test_harness.html#occt_draw_8][Data Exchange]]

Commands for loading IGES/STEP files

**** Geometry Commands

This will be more interesting if data is loaded from a file

+ beziercurve
+ bsplinecurve

*** Errors

The docs mention that =$CASROOT/src/

**** Clicking anything in "File" :: bgerror failed to handle background error.
**** Clicking Samples > View Samples :: Original error: no files matched glob pattern "*.tcl"
